
version: 2
jobs:
  build:
    docker:
      - image: golang:1.14-alpine

    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout

      - run: go build ./cmd/votelistener/main.go

      - store_artifacts:
          path: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}/main
          name: main